export const environment = {
  production: true,
  apiUrl: 'https://woocommerce.rshossain.com/wp-json',
  woocommerceApi: 'https://woocommerce.rshossain.com/wp-json/wc/v3',
  storeApi: 'https://woocommerce.rshossain.com/wp-json/wc/store/v1',
  customApi: 'https://woocommerce.rshossain.com/wp-json/wc-angular/v1',
  reviewsApi: 'https://woocommerce.rshossain.com/wp-json/custom/v1',
  consumerKey: 'ck_8fde1482ddc884c1c36fdfcd26699c8970bd8faa',
  consumerSecret: 'cs_96a821759a1f187b1af994802b932524c02b1834',
  stripePublishableKey: 'pk_live_your_stripe_key',
  googleAnalyticsId: 'G-XXXXXXXXXX',
  defaultCurrency: 'USD',
  defaultLanguage: 'en',
  itemsPerPage: 12,
};